name = "DebugAdapter"
uuid = "17994d07-08fe-42cc-bc1b-7af499b1ea47"
version = "1.0.1-DEV"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
JuliaInterpreter = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
JSONRPC = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
JSON = "0.20, 0.21"
julia = "1"
JuliaInterpreter = "0.8.5, 0.9"
JSONRPC = "1.1"

[targets]
test = ["Test"]
