name = "JSONRPC"
uuid = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "1.3.5-DEV"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
JSON = "0.20, 0.21"
julia = "1"

[targets]
test = ["Test", "Sockets"]
