name = "StaticLint"
uuid = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
version = "8.1.1-DEV"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
CSTParser = "3.3"
SymbolServer = "5.1.1, 6.0, 7.0"

[targets]
test = ["Test", "Pkg", "SHA", "LibGit2"]
